/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link RobotgeneratorWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRobotgeneratorWebModule extends DefaultWebModule {

}
