/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.web;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class RobotgeneratorWebModule extends AbstractRobotgeneratorWebModule {
}
