/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.gunnarkleiven.robotgenerator.RobotgeneratorRuntimeModule;
import org.gunnarkleiven.robotgenerator.RobotgeneratorStandaloneSetup;
import org.gunnarkleiven.robotgenerator.ide.RobotgeneratorIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class RobotgeneratorWebSetup extends RobotgeneratorStandaloneSetup {
  @Override
  public Injector createInjector() {
    RobotgeneratorRuntimeModule _robotgeneratorRuntimeModule = new RobotgeneratorRuntimeModule();
    RobotgeneratorIdeModule _robotgeneratorIdeModule = new RobotgeneratorIdeModule();
    RobotgeneratorWebModule _robotgeneratorWebModule = new RobotgeneratorWebModule();
    return Guice.createInjector(Modules2.mixin(_robotgeneratorRuntimeModule, _robotgeneratorIdeModule, _robotgeneratorWebModule));
  }
}
