/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotgeneratorScopeProvider extends DelegatingScopeProvider {
}
