/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.robotgenerator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getAddRobot()
 * @model
 * @generated
 */
public interface AddRobot extends CommandType
{
} // AddRobot
