/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.robotgenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getCommandType <em>Command Type</em>}</li>
 *   <li>{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getRobotType <em>Robot Type</em>}</li>
 *   <li>{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getRobotName <em>Robot Name</em>}</li>
 *   <li>{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getXValue <em>XValue</em>}</li>
 *   <li>{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getYValue <em>YValue</em>}</li>
 * </ul>
 *
 * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
  /**
   * Returns the value of the '<em><b>Command Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command Type</em>' containment reference.
   * @see #setCommandType(CommandType)
   * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getCommand_CommandType()
   * @model containment="true"
   * @generated
   */
  CommandType getCommandType();

  /**
   * Sets the value of the '{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getCommandType <em>Command Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command Type</em>' containment reference.
   * @see #getCommandType()
   * @generated
   */
  void setCommandType(CommandType value);

  /**
   * Returns the value of the '<em><b>Robot Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.gunnarkleiven.robotgenerator.robotgenerator.RobotType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robot Type</em>' attribute.
   * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotType
   * @see #setRobotType(RobotType)
   * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getCommand_RobotType()
   * @model
   * @generated
   */
  RobotType getRobotType();

  /**
   * Sets the value of the '{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getRobotType <em>Robot Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robot Type</em>' attribute.
   * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotType
   * @see #getRobotType()
   * @generated
   */
  void setRobotType(RobotType value);

  /**
   * Returns the value of the '<em><b>Robot Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robot Name</em>' containment reference.
   * @see #setRobotName(RobotName)
   * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getCommand_RobotName()
   * @model containment="true"
   * @generated
   */
  RobotName getRobotName();

  /**
   * Sets the value of the '{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getRobotName <em>Robot Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robot Name</em>' containment reference.
   * @see #getRobotName()
   * @generated
   */
  void setRobotName(RobotName value);

  /**
   * Returns the value of the '<em><b>XValue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>XValue</em>' containment reference.
   * @see #setXValue(PositionValue)
   * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getCommand_XValue()
   * @model containment="true"
   * @generated
   */
  PositionValue getXValue();

  /**
   * Sets the value of the '{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getXValue <em>XValue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>XValue</em>' containment reference.
   * @see #getXValue()
   * @generated
   */
  void setXValue(PositionValue value);

  /**
   * Returns the value of the '<em><b>YValue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>YValue</em>' containment reference.
   * @see #setYValue(PositionValue)
   * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getCommand_YValue()
   * @model containment="true"
   * @generated
   */
  PositionValue getYValue();

  /**
   * Sets the value of the '{@link org.gunnarkleiven.robotgenerator.robotgenerator.Command#getYValue <em>YValue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>YValue</em>' containment reference.
   * @see #getYValue()
   * @generated
   */
  void setYValue(PositionValue value);

} // Command
