/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.robotgenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Position Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gunnarkleiven.robotgenerator.robotgenerator.PositionValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getPositionValue()
 * @model
 * @generated
 */
public interface PositionValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage#getPositionValue_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.gunnarkleiven.robotgenerator.robotgenerator.PositionValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // PositionValue
