/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.robotgenerator;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage
 * @generated
 */
public interface RobotgeneratorFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RobotgeneratorFactory eINSTANCE = org.gunnarkleiven.robotgenerator.robotgenerator.impl.RobotgeneratorFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command</em>'.
   * @generated
   */
  Command createCommand();

  /**
   * Returns a new object of class '<em>Robot Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Robot Name</em>'.
   * @generated
   */
  RobotName createRobotName();

  /**
   * Returns a new object of class '<em>Position Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Position Value</em>'.
   * @generated
   */
  PositionValue createPositionValue();

  /**
   * Returns a new object of class '<em>Command Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command Type</em>'.
   * @generated
   */
  CommandType createCommandType();

  /**
   * Returns a new object of class '<em>Add Robot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Robot</em>'.
   * @generated
   */
  AddRobot createAddRobot();

  /**
   * Returns a new object of class '<em>Remove Robot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Remove Robot</em>'.
   * @generated
   */
  RemoveRobot createRemoveRobot();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RobotgeneratorPackage getRobotgeneratorPackage();

} //RobotgeneratorFactory
