/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.gunnarkleiven.robotgenerator.RobotgeneratorRuntimeModule;
import org.gunnarkleiven.robotgenerator.RobotgeneratorStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RobotgeneratorIdeSetup extends RobotgeneratorStandaloneSetup {
  @Override
  public Injector createInjector() {
    RobotgeneratorRuntimeModule _robotgeneratorRuntimeModule = new RobotgeneratorRuntimeModule();
    RobotgeneratorIdeModule _robotgeneratorIdeModule = new RobotgeneratorIdeModule();
    return Guice.createInjector(Modules2.mixin(_robotgeneratorRuntimeModule, _robotgeneratorIdeModule));
  }
}
