/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.gunnarkleiven.robotgenerator.ui.internal.RobotgeneratorActivator;

public class RobotgeneratorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotgeneratorActivator.getInstance().getInjector("org.gunnarkleiven.robotgenerator.Robotgenerator");
	}

}
