/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.ide


/**
 * Use this class to register ide components.
 */
class RobotgeneratorIdeModule extends AbstractRobotgeneratorIdeModule {
}
