/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RobotgeneratorAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/gunnarkleiven/robotgenerator/parser/antlr/internal/InternalRobotgenerator.tokens");
	}
}
