/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gunnarkleiven.robotgenerator.parser.antlr.internal.InternalRobotgeneratorParser;
import org.gunnarkleiven.robotgenerator.services.RobotgeneratorGrammarAccess;

public class RobotgeneratorParser extends AbstractAntlrParser {

	@Inject
	private RobotgeneratorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRobotgeneratorParser createParser(XtextTokenStream stream) {
		return new InternalRobotgeneratorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RobotgeneratorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RobotgeneratorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
