/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRobotgeneratorValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage.eINSTANCE);
		return result;
	}
}
