/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RobotgeneratorUiModule extends AbstractRobotgeneratorUiModule {
  public RobotgeneratorUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
