/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class RobotgeneratorUiModule extends AbstractRobotgeneratorUiModule {
}
