/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RobotgeneratorStandaloneSetup extends RobotgeneratorStandaloneSetupGenerated {

	def static void doSetup() {
		new RobotgeneratorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
