/*
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RobotgeneratorRuntimeModule extends AbstractRobotgeneratorRuntimeModule {
}
