/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RobotgeneratorStandaloneSetup extends RobotgeneratorStandaloneSetupGenerated {
  public static void doSetup() {
    new RobotgeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
