import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { RobotGeneratorGeneratedModule, RobotGeneratorGeneratedSharedModule } from './generated/module';
import { RobotGeneratorValidationRegistry, RobotGeneratorValidator } from './robot-generator-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RobotGeneratorAddedServices = {
    validation: {
        RobotGeneratorValidator: RobotGeneratorValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RobotGeneratorServices = LangiumServices & RobotGeneratorAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RobotGeneratorModule: Module<RobotGeneratorServices, PartialLangiumServices & RobotGeneratorAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new RobotGeneratorValidationRegistry(services),
        RobotGeneratorValidator: () => new RobotGeneratorValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRobotGeneratorServices(context?: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    RobotGenerator: RobotGeneratorServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RobotGeneratorGeneratedSharedModule
    );
    const RobotGenerator = inject(
        createDefaultModule({ shared }),
        RobotGeneratorGeneratedModule,
        RobotGeneratorModule
    );
    shared.ServiceRegistry.register(RobotGenerator);
    return { shared, RobotGenerator };
}
