/**
 * generated by Xtext 2.25.0
 */
package org.gunnarkleiven.robotgenerator.robotgenerator.impl;

import org.eclipse.emf.ecore.EClass;

import org.gunnarkleiven.robotgenerator.robotgenerator.AddRobot;
import org.gunnarkleiven.robotgenerator.robotgenerator.RobotgeneratorPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Add Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AddRobotImpl extends CommandTypeImpl implements AddRobot
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AddRobotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RobotgeneratorPackage.Literals.ADD_ROBOT;
  }

} //AddRobotImpl
